[project]
name = "io-local-personal-helpers"
dynamic = ["version"]
description = "A wrapper CLI for system administration commands on Ubuntu."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
os = "oswrap.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/oswrap/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/oswrap"]
