#!/usr/bin/env python3

def show_help() -> None:
    print("os - System helper command")
    print("")
    print("Description:")
    print("  The 'os' command is an entry point to manage basic")
    print("  system administration tasks for Ubuntu 24.04 LTS.")
    print("  At this stage it provides help, update and upgrade routines.")
    print("")
    print("Usage:")
    print("  os")
    print("  os help")
    print("  os --help")
    print("  os update")
    print("")
    print("Options:")
    print("  help       Show this help message.")
    print("  --help     Show this help message.")
    print("  update     Run 'sudo apt -y update --fix-missing' followed by")
    print("             listing upgradable packages and 'sudo apt -y upgrade' if")
    print("             the user is in the sudo group.")
    print("  -v, --verbose  Print full command output to the terminal while still")
    print("                 writing the same output to the execution log.")
    print("")
    print("Notes:")
    print("  This tool is under development and will be extended with more")
    print("  system management capabilities.")
